# Generated by Django 4.1.5 on 2023-02-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category_product_product_statuc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_statuc',
            new_name='product_status',
        ),
    ]
