# Generated by Django 4.1.5 on 2023-02-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_liked_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('Активный', 'Активный'), ('На модерации', 'На модерации'), ('Не активный', 'Не активный'), ('Откланён', 'Откланён')], default='Активный', max_length=35),
        ),
    ]
