# Generated by Django 4.1.5 on 2023-02-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseted_passwords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='about_self',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
